### ISSUE TITLE
Crash upon load, likely incompatibility with other mod, but may be something else.

### ISSUE THREAD

**Issue by cproo12** [boyonk913/music-sync#2]
Log link: https://mclo.gs/q1JuZGa
[latest.log file (same as link)](https://github.com/boyonk913/music-sync/files/15154938/latest.log)

I have many other mods installed, but the error doesn't help me narrow down the incompatibility. Love this mod and would love to be able to use it in my pack.

Willing to help you debug!!!

**Comment by boyonk913** [comment]
Hi!

This was a stupid mistake I made on my end.
It should be resolved as of version 1.3, which is available for Minecraft 1.16-1.20.6.

Thanks for the report. I would not have caught this without you!

**Comment by cproo12** [comment]
awesome!! Thanks really appreciate it!
